<?php


/**
 * @file
 * Contains exchange_rates.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function exchange_rates_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exchange_rates module.
    case 'help.page.exchange_rates':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module converts a base currency into multiple foreign currencies using exchangeratesapi.io.') . '</p>';
      return $output;

    default:
  }
}

// set API Endpoint and API key
$endpoint = 'http://api.exchangeratesapi.io/v1/latest';
$access_key = 'a7fabae09597603417d55a2b1f03bfb1';

// Initialize CURL:
$ch = curl_init('https://api.exchangeratesapi.io/v1/'.$endpoint.'?access_key='.$access_key.'');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

// Store the data:
$json = curl_exec($ch);
curl_close($ch);

// Decode JSON response:
$exchangeRates = json_decode($json, true);

// Access the exchange rate values, e.g. GBP:
echo $exchangeRates['rates']['USD']['EUR']['RUB']['UAH'];