base_currency: USD
conversion_currency:
  - EUR
  - RUB
currency:
  AUD: 'Australian Dollar (A$)'
  BGN: 'Bulgarian Lev (BGN)'
  BRL: 'Brazilian Real (R$)'
  CAD: 'Canadian Dollar (CA$)'
  CHF: 'Swiss Franc (CHF)'
  CNY: 'Chinese Yuan (CN¥)'
  CZK: 'Czech Republic Koruna (CZK)'
  DKK: 'Danish Krone (DKK)'
  EUR: 'Euro (€)'
  GBP: 'British Pound (£)'
  HKD: 'Hong Kong Dollar (HK$)'
  HRK: 'Croatian Kuna (HRK)'
  HUF: 'Hungarian Forint (HUF)'
  IDR: 'Indonesian Rupiah (IDR)'
  ILS: 'Israeli New Sheqel (₪)'
  INR: 'Indian Rupee (Rs.)'
  ISK: 'Icelandic Króna (ISK)'
  JPY: 'Japanese Yen (¥)'
  KRW: 'South Korean Won (₩)'
  MXN: 'Mexican Peso (MX$)'
  MYR: 'Malaysian Ringgit (MYR)'
  NOK: 'Norwegian Krone (NOK)'
  NZD: 'New Zealand Dollar (NZ$)'
  PHP: 'Philippine Peso (Php)'
  PLN: 'Polish Zloty (PLN)'
  RON: 'Romanian Leu (RON)'
  RUB: 'Russian Ruble (RUB)'
  SEK: 'Swedish Krona (SEK)'
  SGD: 'Singapore Dollar (SGD)'
  THB: 'Thai Baht (THB)'
  TRY: 'Turkish Lira (TRY)'
  USD: 'US Dollar ($)'
  ZAR: 'South African Rand (ZAR)'
_core:
  default_config_hash: Fo2dF_oa3ldOsu2YNXmYUI0RqjKWXPQnptjDkgNLbQA
